/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class homework9 */

#ifndef _Included_homework9
#define _Included_homework9
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     homework9
 * Method:    is_multiple4
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_homework9_is_1multiple4
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
